# SPDX-FileCopyrightText: Chris Montgomery <chmont@protonmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later
{
  perSystem =
    { config, pkgs, ... }:
    {
      pre-commit.settings = {
        hooks = {
          biome = {
            enable = true;
            settings = {
              write = false; # formatting handled by treefmt
              configPath = "biome.json";
            };
          };
          markdownlint.enable = true;
          markdownlint.excludes = [
            # Auto-generated
            "CHANGELOG.md"
          ];
          reuse = {
            enable = true;
            stages = [ "pre-push" ];
          };
          treefmt.enable = true;
          yamllint.enable = true;
        };
        default_stages = [
          "pre-commit"
          "pre-push"
        ];
        excludes = [
          # Generated by Copier
          "\\.copier-answers\\.yml$"
        ];
      };
    };
}
